export enum MapType {
    ARCHIPELAGO = 1,
    INLAND_SEA = 2,
    HIGHLAND = 3,
    ISLANDS = 4,
    SMALL_CONTINENTS = 5,
    CONTINENTS = 6,
    CONTINENTS_ISLANDS = 7,
    SUPER_CONTINENT = 8,
    LAKES = 9,
}